### PR TITLE
Add Makefile entity for riscv64

### PR DESCRIPTION
**Pull request by Clansty**
Add Makefile entity for riscv64

### CODE REVIEW

**Comment by Clansty** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by Clansty** [comment]
recheck

**Comment by Zeno-sole** [comment]
@Clansty  更正一下你的commit 信息，参考历史提交

**Comment by Clansty** [comment]
应该好了

**Review by Zeno-sole — APPROVED** [review]

**Pull request merged**
